site_name: Guia de Programação Competitiva UTFPR

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md

  - Introdução:
    - Tests: tests/test.md
    - O que é Programação Competitiva: getting-started/what-is-cp.md
