site_name: Guia de Programação Competitiva UTFPR
site_description: Guia para estudo e treinamento em Programação Competitiva da UTFPR.

site_url: https://eduardo-marca.github.io/utfpr-guia-programacao-competitiva/

repo_url: https://github.com/eduardo-marca/utfpr-guia-programacao-competitiva
repo_name: utfpr-guia-programacao-competitiva

edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.svg
  language: pt-BR
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/git-alt

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Trocar para modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Trocar para modo claro

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mermaid2

extra_css:
  - stylesheets/style.css

extra_javascript:
  - javascripts/script.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
    - introduction/what-is-cp.md
    - introduction/learning-path.md

  - C++:
    - Básico do C++: cpp/basics.md
    - STL: cpp/stl.md
  
  - Algoritmos Básicos:
    - Busca Binária: algorithms/basic-algorithms/binary-search.md

  - Paradigmas:
    - Busca Completa: algorithms/paradigms/complete-search.md
    - Algoritmos Gulosos: algorithms/paradigms/greedy.md
    - Programação Dinâmica: algorithms/paradigms/dynamic-programming.md

  - Grafos:
    - DFS: algorithms/graphs/dfs.md
    - BFS: algorithms/graphs/bfs.md

  - Strings:
    - KMP: algorithms/string/kmp.md

  - Matemática:
    - algorithms/math/combinatorics.md
    - algorithms/math/number_theory.md

  - Como Contribuir:
    - contribute/index.md
    - contribute/installation.md
    - contribute/github.md
    - contribute/mkdocs.md
    - contribute/writing-guidelines.md
    - contribute/style-guide.md
